resilience4j.circuitbreaker:
  instances:
    oms:
      registerHealthIndicator: true
      slidingWindowSize: 5
      slowCallDurationThreshold: 2s
      slowCallRateThreshold: 10



resilience4j.timelimiter:
  instances:
    oms:
      timeoutDuration: 3s

circuit-breaker:
  degradeGroups:
    - test2
logging:
  level:
    root: INFO
    io.github.resilience4j: DEBUG